# Generated by Django 5.0.2 on 2025-02-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester-I'), (2, 'Semester-II'), (3, 'Semester-III'), (4, 'Semester-IV'), (5, 'Semester-V'), (6, 'Semester-VI'), (7, 'Semester-VII'), (8, 'Semester-VIII'), (9, 'Semester-IX'), (10, 'Semester-X')]),
        ),
    ]
