# Generated by Django 5.0.2 on 2025-02-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_course_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='email',
        ),
        migrations.AddField(
            model_name='faculty',
            name='subject',
            field=models.CharField(default='Unknown Subject', max_length=100),
        ),
    ]
