# Generated by Django 5.0.2 on 2025-02-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_remove_faculty_email_faculty_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='room',
        ),
        migrations.AddField(
            model_name='timetable',
            name='classroom',
            field=models.CharField(blank=True, choices=[('Classroom1', 'Classroom 1'), ('Classroom2', 'Classroom 2'), ('Classroom3', 'Classroom 3'), ('Classroom4', 'Classroom 4'), ('Classroom5', 'Classroom 5'), ('Classroom6', 'Classroom 6'), ('Classroom7', 'Classroom 7')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lab',
            field=models.CharField(blank=True, choices=[('Lab1', 'Lab 1'), ('Lab2', 'Lab 2'), ('Lab3', 'Lab 3'), ('Lab4', 'Lab 4')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
