# Generated by Django 5.0.2 on 2025-03-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_timeslot_timetableentry_entry_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='entry_type',
        ),
        migrations.AddField(
            model_name='subject',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
    ]
