# Generated by Django 5.0.2 on 2025-03-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_delete_timeslot_remove_timetableentry_entry_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
    ]
