# Generated by Django 5.0.2 on 2025-03-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_timetableentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'faculty'},
        ),
    ]
