# Generated by Django 5.0.2 on 2025-03-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_alter_faculty_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labsession',
            name='faculty',
        ),
    ]
