# Generated by Django 5.0.2 on 2025-03-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_remove_labsession_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
    ]
