# Generated by Django 5.0.2 on 2025-03-06 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0022_alter_subject_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.subject'),
        ),
    ]
