# Generated by Django 5.0.2 on 2025-03-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0023_timetableentry_is_break_alter_timetableentry_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classroom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='lab_choice',
            field=models.CharField(blank=True, choices=[('Lab 1', 'Lab 1'), ('Lab 2', 'Lab 2'), ('Lab 3', 'Lab 3'), ('Lab 4', 'Lab 4')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='LabSession',
        ),
    ]
