# Generated by Django 5.1.3 on 2025-04-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0024_course_classroom_timetableentry_is_lab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_common',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='track',
            field=models.CharField(blank=True, choices=[('AI-ML', 'AI-ML'), ('Web', 'Web')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='lab_choice',
            field=models.CharField(blank=True, choices=[('Lab 1', 'Lab 1'), ('Lab 2', 'Lab 2'), ('Lab 3', 'Lab 3'), ('Lab 4', 'Lab 4'), ('GPU Lab', 'GPU Lab')], max_length=10, null=True),
        ),
    ]
