# Generated by Django 5.1.3 on 2025-04-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0025_subject_is_common_subject_track_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='track',
            field=models.CharField(choices=[('Web', 'Web'), ('AI-ML', 'AI-ML'), ('Common', 'Common')], default='Common', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('course', 'track', 'day', 'start_time')},
        ),
    ]
