# Generated by Django 5.1.3 on 2025-04-02 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0026_alter_timetableentry_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.course'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='track',
            field=models.CharField(blank=True, choices=[('AI-ML', 'AI-ML'), ('Web', 'Web')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='lab_choice',
            field=models.CharField(blank=True, choices=[('Lab 1', 'Lab 1'), ('Lab 2', 'Lab 2'), ('Lab 3', 'Lab 3'), ('Lab 4', 'Lab 4')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.subject'),
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='track',
        ),
    ]
