# Generated by Django 5.0.2 on 2025-04-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0027_alter_faculty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='custom_note',
            field=models.CharField(blank=True, help_text='Enter custom note (e.g., Seminar, Orientation)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='is_custom_note',
            field=models.BooleanField(default=False, help_text='Tick if this is a custom activity like Project Review'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10),
        ),
    ]
