# Generated by Django 5.0.2 on 2025-04-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0028_timetableentry_custom_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableentry',
            name='custom_note',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='is_custom_note',
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20),
        ),
    ]
