# Generated by Django 5.0.2 on 2025-05-09 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0029_remove_timetableentry_custom_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
