# Generated by Django 5.0.2 on 2025-05-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0030_timetableentry_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
