# Generated by Django 5.0.2 on 2025-05-14 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0031_alter_timetableentry_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableentry',
            name='created_on',
        ),
        migrations.CreateModel(
            name='TimetablePrintDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_date', models.DateField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timetable.course')),
            ],
        ),
    ]
