# Generated by Django 5.0.2 on 2025-05-14 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0032_remove_timetableentry_created_on_timetableprintdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TimetablePrintDate',
        ),
    ]
