# Generated by Django 5.0.2 on 2025-05-15 07:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0033_timetableentry_created_on_delete_timetableprintdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableentry',
            name='created_on',
        ),
        migrations.CreateModel(
            name='TimetablePrintDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_date', models.DateField(default=django.utils.timezone.now)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timetable.course')),
            ],
        ),
    ]
