# Generated by Django 5.0.2 on 2025-05-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0034_remove_timetableentry_created_on_timetableprintdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableprintdate',
            name='effective_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
