# Generated by Django 5.0.2 on 2025-05-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0035_timetableprintdate_effective_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableprintdate',
            name='effective_note',
        ),
        migrations.RemoveField(
            model_name='timetableprintdate',
            name='print_date',
        ),
        migrations.AddField(
            model_name='timetableprintdate',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
